#%RAML 1.0
title: DIY-account-api

types:
  Account_datatype: !include data_types/Account.raml
  
/accounts:
  get:
    description: Get accounts  
    headers:
      user_id:
    queryParameters:
      account_type:
        description: filter based on account-type
        required: false
        enum:
          - personal
          - business 
      account_name:
        description: filter based on account-name
        required: false
    responses:
      200:
        body:
          application/json:
            type: Account_datatype[]
            example: !include examples/Accounts.raml

  
  post:
    description: create account
    headers:
      user_id:
    body:
      application/json:
        type: Account_datatype[]
        example:  !include examples/AccountsnoID.raml
          
    responses:
      201:
        body:
          application/json:
            example: Accounts created successfully!

    
